algoritmo "Média Notas Escolares"

var

Nota1, Nota2, Nota3, Nota4, Media: real

inicio

Escreval ("Qual foi sua nota no primeiro bimestre?")
leia (Nota1)
Escreval ("Qual foi sua nota no segundo bimestre?")
leia (Nota2)
Escreval ("Qual foi sua nota no terceiro bimestre?")
leia (Nota3)
Escreval ("Qual foi sua nota no quarto bimestre?")
leia (Nota4)

Media <- (Nota1 + Nota2 + Nota3 + Nota4)/4
Escreval ("Sua média de notas é ", Media)

fimalgoritmo
